FB0T-136
fratik/FratikB0T pull request #110
Opened 2020-05-22 18:26 UTC by KAMIL0024

2020-05-23 23:42 UTC, fratik requested changes
jestem w szoku że zasugerowałem dosłownie dwie zmiany w kodzie, nice

2020-05-23 23:42 UTC, fratik commented on commands/src/main/java/pl/fratik/commands/system/UstawPoziomCommand.java
> +            }
to nie wywali błędu, get zwraca nulla jak nie znajdzie

```suggestion
            ccmd = managerKomend.getCommands().get(cmd);
```

2020-05-23 23:42 UTC, fratik commented on commands/src/main/java/pl/fratik/commands/system/UstawPoziomCommand.java
> +            if (ccmd.getPermLevel().getNum() > 4) {
lepiej nie ustawiać na twardo - dałbym `>= PermLevel.GADMIN.getNum()`

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +generic.cooldown=Musisz poczekać %s sek. przed następnym użyciem komendy\!
```suggestion
generic.cooldown=Musisz poczekać %s sek. przed następnym użyciem tej komendy\!
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.help.description=Ustawia poziom uprawnień dla danej komendy
```suggestion
ustawpoziom.help.description=Nadpisuje poziom uprawnień dla danej komendy
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.list.desc=%s - %s (%s poziom)
chyba tak by bardziej pasowało
```suggestion
ustawpoziom.list.desc=%s - %s (poziom %s)
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.set.nopermissions=Prawdopodobnie próbujesz ustawić poziom dla komendy do, której nie masz permisji lub chcesz ustawić poziom większy od twojego
jak już bawimy się w interpunkcję-
```suggestion
ustawpoziom.set.nopermissions=Prawdopodobnie próbujesz ustawić poziom dla komendy, do której nie masz uprawnień, lub chcesz ustawić poziom większy od swojego
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.remove.doesnt.exist=Taka komenda nie ma zmienionego poziomu uprawnień!
```suggestion
ustawpoziom.remove.doesnt.exist=Ta komenda nie ma nadpisanego poziomu uprawnień!
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.set.poziomcmd=Nie możesz zmieniać poziomu uprawnień dla tej komendy!
```suggestion
ustawpoziom.set.poziomcmd=Nie możesz nadpisać poziomu uprawnień dla tej komendy!
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.set.succes=Pomyślnie zmieniono poziom uprawnień dla komendy `%s` na %s (%s)
```suggestion
ustawpoziom.set.succes=Pomyślnie nadpisano poziom uprawnień dla komendy `%s` na %s (%s)
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.list.isempty=Żadna komenda nie ma ustawionego poziomu uprawnień!
```suggestion
ustawpoziom.list.isempty=Żadna komenda nie ma nadpisanego poziomu uprawnień!
```

2020-05-23 23:42 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +ustawpoziom.set.gacmd=Nie możesz ustawić poziomu uprawnień dla tej komendy. Najprawdopodobniej jest ona przeznaczona TYLKO dla Global Administratorów bota lub Deweloperów
```suggestion
ustawpoziom.set.gacmd=Nie możesz nadpisać poziomu uprawnień dla tej komendy. Najprawdopodobniej jest ona przeznaczona TYLKO dla Global Administratorów bota lub Deweloperów.
```

2020-05-24 00:13 UTC, KAMIL0024 commented on commands/src/main/java/pl/fratik/commands/system/UstawPoziomCommand.java
> +            if (ccmd.getPermLevel().getNum() > 4) {
XD, patrzenie na #struktura-uprawnien weszlo za mocno

2020-05-24 00:16 UTC, KAMIL0024 commented
To znaczy tylko jedno... coś ci umknęło

2020-07-08 20:21 UTC, fratik requested changes
zajmę się tym, jak coś

2020-07-08 20:21 UTC, fratik commented on core/src/main/java/pl/fratik/core/manager/implementation/ManagerKomendImpl.java
> +                GuildConfig gc = guildDao.get(event.getGuild());
trzeba cache'ować gc, napierdzielanie w db co komendę może być złym pomysłem XD

2020-07-08 23:11 UTC, fratik submitted a review, later dismissed
kod wydaje się git, ale nie ufam sobie na tyle by to puścić bez testów XD

2020-07-08 23:17 UTC, fratik submitted a review, later dismissed
j/w

2020-07-09 21:00 UTC, fratik approved these changes
a więc działa

2020-07-09 21:04 UTC, merged