FB0T-99
fratik/FratikB0T pull request #3
Opened 2019-11-07 16:18 UTC by KAMIL0024

2019-11-07 16:20 UTC, KAMIL0024 commented
Czemu dało FB0T-99 skoro to inny branch jest, a 99 ma juz pulla xD

2019-11-07 16:32 UTC, fratik commented
nie mam pojęcia, ale trzeba będzie force pushnąć by tego nie było zanim się konflikty porobią

2019-11-07 16:33 UTC, fratik submitted a review, later dismissed

2019-11-07 16:37 UTC, fratik submitted a review, later dismissed

2019-11-08 13:45 UTC, fratik requested changes

2019-11-08 13:45 UTC, fratik commented on core/src/main/java/pl/fratik/core/command/CommandContext.java
> +    public String getManageLink(Guild g) {
to to w takim razie wywal~

2019-11-08 13:46 UTC, KAMIL0024 commented on core/src/main/java/pl/fratik/core/command/CommandContext.java
> +    public String getManageLink(Guild g) {
hahah

2019-11-08 19:00 UTC, fratik approved these changes

2019-11-08 19:00 UTC, merged