FB0T-28 Lvlup w DM
fratik/FratikB0T pull request #6
Opened 2019-11-07 18:55 UTC by KAMIL0024

2019-11-07 19:08 UTC, fratik requested changes

2019-11-07 19:08 UTC, fratik commented on punkty/src/main/java/pl/fratik/punkty/LicznikPunktow.java
> +            if (uc.isLvlUpOnDM() == false) {
a !uc.isLvlUpOnDm() to nie jest lepsze rozwiazanie?

2019-11-07 19:08 UTC, fratik commented on punkty/src/main/java/pl/fratik/punkty/LicznikPunktow.java
> +            } catch (ErrorResponseException e) {
lepiej cały Exception catchnąć imo

2019-11-07 19:08 UTC, fratik commented on core/src/main/resources/pl/messages.properties
> +generic.lvlup.dm=Właśnie dostałeś/aś się na poziom **%s** na serwerze %s! Czy to nie super? (więcej informacji? wpisz %sstaty)
daj serwer w pogrubiony tekst

2019-11-08 19:18 UTC, fratik submitted a review, later dismissed

2019-12-04 20:19 UTC, fratik requested changes

2019-12-04 20:19 UTC, fratik commented on commands/src/main/java/pl/fratik/commands/util/OldSettingsRenderer.java
>                  (userConfig.isPrivWlaczone() ? "enabled" : "disabled")));
Kamil plz

2019-12-04 20:19 UTC, fratik commented on commands/src/main/java/pl/fratik/commands/util/OldSettingsRenderer.java
> +                        (userConfig.isPrivWlaczone() ? "enabled" : "disabled")));
v2

2019-12-04 20:19 UTC, fratik commented on commands/src/main/java/pl/fratik/commands/util/OldSettingsRenderer.java
> +                userConfig.setLvlupMessages(!userConfig.isLvlUpOnDM());
`setLvlupMessages(isLvlUpOnDM)`
seems legit

2019-12-04 20:19 UTC, fratik commented on .idea/compiler.xml
> +      <module name="fratikbot.liczek.test" target="1.8" />
po 👏 co 👏 tu 👏 liczek

2019-12-04 20:19 UTC, fratik commented on .idea/compiler.xml
> +      <module name="fratikbot.liczek.test" target="1.8" />
(konflikty się porobią)

2019-12-04 20:21 UTC, KAMIL0024 commented on .idea/compiler.xml
> +      <module name="fratikbot.liczek.test" target="1.8" />
TO TA GLUPIA IDEA

2019-12-04 20:23 UTC, fratik commented
nvm ja to wszystko zjebałem

2019-12-04 20:37 UTC, fratik approved these changes

2019-12-04 21:16 UTC, merged